const products = [
    {
        id:1,
        title:"Nike Flight Legacy",
        desc:"Flight Legacy Sneakers For Men  (White)",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/h/m/8-bq4212-100-8-nike-white-original-imagqzkv6gyupkuh.jpeg?q=70",
        price:6875.00,
        rating:4.45,
        discount:15,
        category:"Sneakers",
        link:"/products/1",
        tags:"Top"
    },
    {
        id:2,
        title:"MacBook Pro",
        desc:"MacBook Pro 2021 with mini-LED display may launch between September, November",
        thumbnail:"https://rukminim2.flixcart.com/image/312/312/kuyf8nk0/computer/3/n/s/mk183hn-a-laptop-apple-original-imag7yzkbgbwvwq3.jpeg?q=70",
        price:1200.00,
        rating:4.57,
        discount:15,
        category:"Electronics",
        link:"/products/2",
        tags:"Top"
    },
    {
        id:3,
        title:"Boat Rockerz 235 V2",
        desc:"Bluetooth Stereo Wireless Earphone with Up to 8 Hours of Uninterrupted Music, Fast Charging, IPX5 sweat and water resistance",
        thumbnail:"https://cdn.shopify.com/s/files/1/0057/8938/4802/products/ed46e58c-9643-43e0-b350-9539d293aa51_228x.png?v=1685697420",
        price:2000.00,
        rating:4.45,
        discount:15,
        category:"Electronics",
        link:"/products/3",
        tags:"Top"
    },
    {
        id:4,
        title:"Iphone X",
        desc:"An apple mobile which is nothing like apple",
        thumbnail:"https://rukminim2.flixcart.com/image/312/312/jnj7iq80/mobile/u/b/g/apple-iphone-xr-mryj2hn-a-original-imafa6zkm7qhv2zd.jpeg?q=70",
        price:700.00,
        rating:4.45,
        discount:15,
        category:"Mobiles",
        link:"/products/4",
        tags:"Top"
    },
    {
        id:5,
        title:"Black T-shirt",
        desc:"Black T-shirt with black text in grey box",
        thumbnail:"https://img.freepik.com/free-psd/mens-tri-blend-crew-tee-mockup_126278-130.jpg?w=740&t=st=1692137210~exp=1692137810~hmac=5dfa1eceebb4748921d710cb46a4149a5bcd4c3698ca1243a62730643d456082",
        price:300.00,
        rating:4.45,
        discount:15,
        category:"Fashion",
        link:"/products/5",
        tags:"Top"
    },
    {
        id:6,
        title:"Avengers T-shirt",
        desc:"Marvel Avengers 'Legends Never Die' Black T-Shirt",
        thumbnail:"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSRArCLhGX_3aOumUlm1_CY96tEiTpwfefIdrthvwJrS1ewyweUkNhg85rSuLqj7gRlTncRKRqoQoS5VeKJfmvSbfhP3YUAAeSOgDjNbKcd2A-ZROrbwuaI",
        price:499.00,
        rating:4.03,
        discount:15,
        category:"Fashion",
        link:"/products/6",
        tags:"Best-Seller"
    },
    {
        id:7,
        title:"White Jeans",
        desc:"Mid Rise White Jeans",
        thumbnail:"https://rukminim2.flixcart.com/image/612/612/kc0u7bk0/jean/f/i/y/30-30-beg-fashion-original-imaft7zgjv5wgumh.jpeg?q=70",
        price:369.00,
        rating:3.87,
        discount:15,
        category:"Fashion",
        link:"/products/7",
        tags:"Best-Seller"
    },
    {
        id:8,
        title:"Sweat Pants-Pair Of Two",
        desc:"Pack of 2 Men Solid Grey Track Pants",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
        price:2000.00,
        rating:3.95,
        discount:60,
        category:"Fashion",
        link:"/products/8",
        tags:"Heavily-Discounted"
    },
    {
        id:9,
        title:"White Shoes",
        desc:"High Tops For Men (White)",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/i/6/6-jimny-white-6-sfr-white-original-imagnp4zhejww3uf.jpeg?q=70",
        price:1000.00,
        rating:3.50,
        discount:60,
        category:"Sneakers",
        link:"/products/9",
        tags:"Heavily-Discounted"
    },
    {
        id:10,
        title:"Puma Sneakers",
        desc:"Rebound LayUp SL Sneakers For Men",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/l/r/v/10-369573-10-puma-parisian-night-high-risk-red-white-original-imaghbgnufgqtrgt.jpeg?q=70",
        price:5000,
        rating:4.50,
        discount:20,
        category:"Sneakers",
        link:"/products/10",
        tags:"Best-Seller"
    },
    {
        id:11,
        title:"White-Navy Sneakers",
        desc:"Sneakers For Men",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/shoe/f/y/x/8-tarzan-04-asian-white-navy-grey-original-imagppfwgmac78ay.jpeg?q=70",
        price:900,
        rating:4.00,
        discount:30,
        category:"Sneakers",
        link:"/products/11",
        tags:"Top"
    },
    {
        id:12,
        title:"Puma Glory Sneakers",
        desc:"Puma Glory Sneakers For Men",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/kxtaxzk0/shoe/6/a/j/9-387965-9-puma-black-white-yellow-alert-original-imaga6hm8jnagyay.jpeg?q=70",
        price:3000.00,
        rating:4.3,
        discount:20,
        category:"Sneakers",
        link:"/products/12",
        tags:"Top"
    },
    {
        id:13,
        title:"CLARKIN Sneakers",
        desc:"U.S. POLO ASSN",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/f/5/11-2531910312-11-u-s-polo-assn-off-white-original-imags5qhjgh9sgq2.jpeg?q=70",
        price:10000,
        rating:4.8,
        discount:80,
        category:"Sneakers",
        link:"/products/13",
        tags:"Heavily-Discounted"
    },
    {
        id:14,
        title:"Floral Pattern Casual Shirt",
        desc:"Men Regular Fit Striped Slim Collar Casual Shirt",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/w/g/l/m-mmm-solbiza-original-imagzyastb2kzyvc.jpeg?q=70",
        price:1300.00,
        rating:4.1,
        discount:80,
        category:"Fashion",
        link:"/products/14",
        tags:"Heavily-Discounted"
    },
    {
        id:15,
        title:"Women Hoodie Blue",
        desc:"Women Full Sleeve Printed Hooded Sweatshirt",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/ksnjp8w0/sweatshirt/r/o/b/m-ttss000484-tokyo-talkies-original-imag664kzchgm5h8.jpeg?q=70",
        price:1800.00,
        rating:4.2,
        discount:70,
        category:"Fashion",
        link:"/products/15",
        tags:"Heavily-Discounted"
    },
    {
        id:16,
        title:"Puff Sleeves Top for Women",
        desc:"Casual Puff Sleeves Solid Women Blue Top",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/kr6oeq80/top/g/t/9/xl-top-499-sofia-pista-dream-beauty-fashion-original-imag5f8e6xwfmqjv.jpeg?q=70",
        price:600,
        rating:3.5,
        discount:60,
        category:"Fashion",
        link:"/products/16",
        tags:"Heavily-Discounted"
    },
    {
        id:17,
        title:"Women Kurti",
        desc:"Women Printed Cotton Blend A-line Kurta  (Maroon)",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/u/6/1/xxl-mira-foil-kurti-fashion2wear-original-imaghua4rmpnzwkz.jpeg?q=70",
        price:1000,
        rating:3.7,
        discount:70,
        category:"Fashion",
        link:"/products/17",
        tags:"Heavily-Discounted"
    },
    {
        id:18,
        title:"Yellow Dress",
        desc:"Women Fit and Flare Yellow Dress",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/kq9ta4w0/dress/d/e/p/l-sun-drs-misverse-original-imag4bhgaspwfy4x.jpeg?q=70",
        price:1500.00,
        rating:4.9,
        discount:25,
        category:"Fashion",
        link:"/products/18",
        tags:"Top"
    },
    {
        id:19,
        title:"Floral Sundress",
        desc:"Women Fit and Flare Yellow Dress",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/k5r2mq80/dress/s/q/u/l-269-shivay-style-original-imafn4yf3errmfg4.jpeg?q=70",
        price:1000.00,
        rating:3.9,
        discount:60,
        category:"Fashion",
        link:"/products/19",
        tags:"Heavily-Discounted"
    },
    {
        id:20,
        title:"Black Top",
        desc:"Party Flared Sleeves Printed, Graphic Print, Solid Women Black Top",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/top/4/n/h/xs-queen-eddlees-original-imaggnexgy2fwuez.jpeg?q=70",
        price:750,
        rating:4.95,
        discount:33,
        category:"Fashion",
        link:"/products/20",
        tags:"Best-Seller"
    },
    {
        id:21,
        title:"Sleevless Top for Women",
        desc:"Casual Cap Sleeves Self Design Women Dark Blue Top",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/top/b/i/j/xxl-prw-482-prettify-original-imagptv46fmhbtzb.jpeg?q=70",
        price:1700.00,
        rating:4.1,
        discount:77,
        category:"Fashion",
        link:"/products/21",
        tags:"Heavily-Discounted"
    }
];

export default products;