const products = [
    {
        id:"1",
        title:"Nike Flight Legacy",
        desc:"Flight Legacy Sneakers For Men  (White)",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/h/m/8-bq4212-100-8-nike-white-original-imagqzkv6gyupkuh.jpeg?q=70",
        price:6875.00,
        rating:4.45,
        discount:15,
        category:"Sneakers",
        link:"/products/1",
        tags:"Top"
    },
    {
        id:2,
        title:"MacBook Pro",
        desc:"MacBook Pro 2021 with mini-LED display may launch between September, November",
        thumbnail:"https://rukminim2.flixcart.com/image/312/312/kuyf8nk0/computer/3/n/s/mk183hn-a-laptop-apple-original-imag7yzkbgbwvwq3.jpeg?q=70",
        price:120000.00,
        rating:4.57,
        discount:15,
        category:"Electronics",
        link:"/products/2",
        tags:"Top"
    },
    {
        id:3,
        title:"Boat Rockerz 235 V2",
        desc:"Bluetooth Stereo Wireless Earphone with Up to 8 Hours of Uninterrupted Music, Fast Charging, IPX5 sweat and water resistance",
        thumbnail:"https://cdn.shopify.com/s/files/1/0057/8938/4802/products/ed46e58c-9643-43e0-b350-9539d293aa51_228x.png?v=1685697420",
        price:2000.00,
        rating:4.45,
        discount:15,
        category:"Electronics",
        link:"/products/3",
        tags:"Top"
    },
    {
        id:4,
        title:"Iphone X",
        desc:"An apple mobile which is nothing like apple",
        thumbnail:"https://rukminim2.flixcart.com/image/312/312/jnj7iq80/mobile/u/b/g/apple-iphone-xr-mryj2hn-a-original-imafa6zkm7qhv2zd.jpeg?q=70",
        price:70000.00,
        rating:4.45,
        discount:15,
        category:"Mobiles",
        link:"/products/4",
        tags:"Top"
    },
    {
        id:5,
        title:"Black T-shirt",
        desc:"Black T-shirt with black text in grey box",
        thumbnail:"https://img.freepik.com/free-psd/mens-tri-blend-crew-tee-mockup_126278-130.jpg?w=740&t=st=1692137210~exp=1692137810~hmac=5dfa1eceebb4748921d710cb46a4149a5bcd4c3698ca1243a62730643d456082",
        price:300.00,
        rating:4.45,
        discount:15,
        category:"Fashion",
        link:"/products/5",
        tags:"Top"
    },
    {
        id:6,
        title:"Avengers T-shirt",
        desc:"Marvel Avengers 'Legends Never Die' Black T-Shirt",
        thumbnail:"https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSRArCLhGX_3aOumUlm1_CY96tEiTpwfefIdrthvwJrS1ewyweUkNhg85rSuLqj7gRlTncRKRqoQoS5VeKJfmvSbfhP3YUAAeSOgDjNbKcd2A-ZROrbwuaI",
        price:499.00,
        rating:4.03,
        discount:15,
        category:"Fashion",
        link:"/products/6",
        tags:"Best-Seller"
    },
    {
        id:7,
        title:"White Jeans",
        desc:"Mid Rise White Jeans",
        thumbnail:"https://rukminim2.flixcart.com/image/612/612/kc0u7bk0/jean/f/i/y/30-30-beg-fashion-original-imaft7zgjv5wgumh.jpeg?q=70",
        price:369.00,
        rating:3.87,
        discount:15,
        category:"Fashion",
        link:"/products/7",
        tags:"Best-Seller"
    },
    {
        id:8,
        title:"Sweat Pants-Pair Of Two",
        desc:"Pack of 2 Men Solid Grey Track Pants",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
        price:2000.00,
        rating:3.95,
        discount:60,
        category:"Fashion",
        link:"/products/8",
        tags:"Heavily-Discounted"
    },
    {
        id:9,
        title:"White Shoes",
        desc:"High Tops For Men (White)",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/k/i/6/6-jimny-white-6-sfr-white-original-imagnp4zhejww3uf.jpeg?q=70",
        price:1000.00,
        rating:3.50,
        discount:60,
        category:"Sneakers",
        link:"/products/9",
        tags:"Heavily-Discounted"
    },
    {
        id:10,
        title:"Puma Sneakers",
        desc:"Rebound LayUp SL Sneakers For Men",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/l/r/v/10-369573-10-puma-parisian-night-high-risk-red-white-original-imaghbgnufgqtrgt.jpeg?q=70",
        price:5000,
        rating:4.50,
        discount:20,
        category:"Sneakers",
        link:"/products/10",
        tags:"Best-Seller"
    },
    {
        id:11,
        title:"White-Navy Sneakers",
        desc:"Sneakers For Men",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/shoe/f/y/x/8-tarzan-04-asian-white-navy-grey-original-imagppfwgmac78ay.jpeg?q=70",
        price:900,
        rating:4.00,
        discount:30,
        category:"Sneakers",
        link:"/products/11",
        tags:"TOp"
    },
    {
        id:12,
        title:"Puma Glory Sneakers",
        desc:"Puma Glory Sneakers For Men",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/kxtaxzk0/shoe/6/a/j/9-387965-9-puma-black-white-yellow-alert-original-imaga6hm8jnagyay.jpeg?q=70",
        price:3000.00,
        rating:4.3,
        discount:20,
        category:"Sneakers",
        link:"/products/12",
        tags:"Top"
    },
    {
        id:13,
        title:"CLARKIN Sneakers",
        desc:"U.S. POLO ASSN",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/f/5/11-2531910312-11-u-s-polo-assn-off-white-original-imags5qhjgh9sgq2.jpeg?q=70",
        price:10000,
        rating:4.8,
        discount:80,
        category:"Sneakers",
        link:"/products/13",
        tags:"Heavily-Discounted"
    },
    {
        id:14,
        title:"Floral Pattern Casual Shirt",
        desc:"Men Regular Fit Striped Slim Collar Casual Shirt",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/w/g/l/m-mmm-solbiza-original-imagzyastb2kzyvc.jpeg?q=70",
        price:1300.00,
        rating:4.1,
        discount:80,
        category:"Fashion",
        link:"/products/14",
        tags:"Heavily-Discounted"
    },
    {
        id:15,
        title:"Women Hoodie Blue",
        desc:"Women Full Sleeve Printed Hooded Sweatshirt",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/ksnjp8w0/sweatshirt/r/o/b/m-ttss000484-tokyo-talkies-original-imag664kzchgm5h8.jpeg?q=70",
        price:1800.00,
        rating:4.2,
        discount:70,
        category:"Fashion",
        link:"/products/15",
        tags:"Heavily-Discounted"
    },
    {
        id:16,
        title:"Puff Sleeves Top for Women",
        desc:"Casual Puff Sleeves Solid Women Blue Top",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/kr6oeq80/top/g/t/9/xl-top-499-sofia-pista-dream-beauty-fashion-original-imag5f8e6xwfmqjv.jpeg?q=70",
        price:600,
        rating:3.5,
        discount:60,
        category:"Fashion",
        link:"/products/16",
        tags:"Heavily-Discounted"
    },
    {
        id:17,
        title:"Women Kurti",
        desc:"Women Printed Cotton Blend A-line Kurta  (Maroon)",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/kurta/u/6/1/xxl-mira-foil-kurti-fashion2wear-original-imaghua4rmpnzwkz.jpeg?q=70",
        price:1000,
        rating:3.7,
        discount:70,
        category:"Fashion",
        link:"/products/17",
        tags:"Heavily-Discounted"
    },
    {
        id:18,
        title:"Yellow Dress",
        desc:"Women Fit and Flare Yellow Dress",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/kq9ta4w0/dress/d/e/p/l-sun-drs-misverse-original-imag4bhgaspwfy4x.jpeg?q=70",
        price:1500.00,
        rating:4.9,
        discount:25,
        category:"Fashion",
        link:"/products/18",
        tags:"Top"
    },
    {
        id:19,
        title:"Floral Sundress",
        desc:"Women Fit and Flare Yellow Dress",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/k5r2mq80/dress/s/q/u/l-269-shivay-style-original-imafn4yf3errmfg4.jpeg?q=70",
        price:1000.00,
        rating:3.9,
        discount:60,
        category:"Fashion",
        link:"/products/19",
        tags:"Heavily-Discounted"
    },
    {
        id:20,
        title:"Black Top",
        desc:"Party Flared Sleeves Printed, Graphic Print, Solid Women Black Top",
        thumbnail:"https://rukminim2.flixcart.com/image/832/832/xif0q/top/4/n/h/xs-queen-eddlees-original-imaggnexgy2fwuez.jpeg?q=70",
        price:750,
        rating:4.95,
        discount:33,
        category:"Fashion",
        link:"/products/20",
        tags:"Best-Seller"
    },
    {
        id:21,
        title:"Sleevless Top for Women",
        desc:"Casual Cap Sleeves Self Design Women Dark Blue Top",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/top/b/i/j/xxl-prw-482-prettify-original-imagptv46fmhbtzb.jpeg?q=70",
        price:1700.00,
        rating:4.1,
        discount:77,
        category:"Fashion",
        link:"/products/21",
        tags:"Heavily-Discounted"
    },
    {
        id:22,
        title:"Noise Colorfit Icon 2",
        desc:"1.8' Display with Bluetooth Calling, AI Voice Assistant Smartwatch  (Black Strap, Regular)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/l5ld8y80/smartwatch/r/q/t/-original-imagg8dksgct9hxg.jpeg?q=70",
        price:6000.00,
        rating:4.2,
        discount:70,
        category:"Electronics",
        link:"/products/22",
        tags:"Heavily-Discounted"
    },
    {
        id:23,
        title:"Fastrack Revoltt FS1",
        desc:"Fastrack Revoltt FS1|1.83 Display|BT Calling|Fastcharge|110+ Sports Mode|200+ WatchFaces Smartwatch  (Black Strap, Free Size)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/smartwatch/k/h/s/1-83-38083pp01-android-ios-fastrack-yes-original-imagnhzeabmcfspe.jpeg?q=70",
        price:3995.00,
        rating:4.2,
        discount:25,
        category:"Electronics",
        link:"/products/23",
        tags:"Best-Seller"
    },
    {
        id:24,
        title:"boAt Wave Neo",
        desc:"boAt Wave Neo with 1.69 inch , 2.5D Curved Display & Multiple Sports Modes Smartwatch  (Active Black Strap, Free Size)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/l3ahpjk0/smartwatch/m/k/a/-original-imagegyhhxaszhn9.jpeg?q=70",
        price:5990.00,
        rating:4.0,
        discount:80,
        category:"Electronics",
        link:"/products/24",
        tags:"Heavily-Discounted"
    },
    {
        id:25,
        title:"HP 15s-fr4000TU Laptop",
        desc:"HP Intel Core i5 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) 15s- fr4000TU Thin and Light Laptop  (15.6 Inch, Natural Silver, 1.69 Kg, With MS Office)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/computer/f/a/8/-original-imagp7pf86vm9mmj.jpeg?q=70",
        price:56903.00,
        rating:4.3,
        discount:10,
        category:"Electronics",
        link:"/products/25",
        tags:"Top"
    },
    {
        id:26,
        title:"Infinix ZEROBOOK ZL513",
        desc:"Infinix ZEROBOOK 13 Intel Core i5 13th Gen - (16 GB/512 GB SSD/Windows 11 Home) ZL513 Thin and Light Laptop  (15.6 inch, Grey With Meteorite Phase Design, 1.80 Kg, With MS Office)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/computer/7/d/i/zl12-business-laptop-infinix-original-imagm83gc6xr8sau.jpeg?q=70",
        price:79990.00,
        rating:4.2,
        discount:30,
        category:"Electronics",
        link:"/products/26",
        tags:"Top"
    },
    {
        id:27,
        title:"boAt Airdopes 131",
        desc:"boAt Airdopes 131 with upto 60 Hours and ASAP Charge Bluetooth Headset  (Active Black, True Wireless)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/1/8/l/-original-imagqhswqgpwb2yu.jpeg?q=70",
        price:2990.00,
        rating:3.7,
        discount:25,
        category:"Electronics",
        link:"/products/27",
        tags:"Best-Seller"
    },
    {
        id:28,
        title:"boAt Rockerz 235 Pro",
        desc:"boAt Rockerz 235 Pro with upto 20 Hours Playback & ASAP Charge Bluetooth Headset  (Active Black, In the Ear)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/l2jcccw0/headphone/p/y/v/-original-imagduskcc5srd3z.jpeg?q=70",
        price:2490.00,
        rating:4.2,
        discount:33,
        category:"Electronics",
        link:"/products/28",
        tags:"Best-Seller"
    },
    {
        id:29,
        title:"Wings Vader 100",
        desc:"Wings Vader 100 Wired Gaming Headset  (Red, On the Ear)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/l09w8sw0/headphone/0/r/x/-original-imagc3grgj9expw9.jpeg?q=70",
        price:1799.00,
        rating:4.1,
        discount:55,
        category:"Electronics",
        link:"/products/29",
        tags:"Heavily-Discounted"
    }, 
    {
        id:30,
        title:"boAt Avante Bar Thump",
        desc:"boAt Aavante Bar Thump with 200W RMS, 2.1 CH with Wired Subwoofer 200 W Bluetooth Soundbar  (Carbon Black, 2.1 Channel)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/speaker/t/b/f/-original-imagnraygvpxhbhv.jpeg?q=70",
        price:22990.00,
        rating:4.3,
        discount:56,
        category:"Electronics",
        link:"/products/30",
        tags:"Heavily-Discounted"
    },
    {
        id:31,
        title:"boAt Stone 350",
        desc:"boAt Stone 350 10 W Bluetooth Speaker  (Blue, Mono Channel)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/kingqkw0-0/speaker/mobile-tablet-speaker/u/1/2/stone-350-boat-original-imafyebfjguufap8.jpeg?q=70",
        price:3490.00,
        rating:4.3,
        discount:59,
        category:"Electronics",
        link:"/products/31",
        tags:"Top"
    },
    {
        id:32,
        title:"Nokia 3310",
        desc:"Nokia 3310 DS 2020  (Dark Blue)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/ka5oia80/mobile/3/h/u/nokia-3310-ds-ta-1030-nokia-3310-ds-original-imafrsgdyzskfhup.jpeg?q=70",
        price:4599.00,
        rating:3.5,
        discount:10,
        category:"Mobiles",
        link:"/products/32",
        tags:"Top"
    },
    {
        id:33,
        title:"SAMSUNG Galaxy F14 5G",
        desc:"SAMSUNG Galaxy F14 5G (GOAT Green, 128 GB)  (6 GB RAM)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/j/i/k/galaxy-f14-5g-sm-e146bzggins-samsung-original-imagnzdkprfwj9hv.jpeg?q=70",
        price:18490.00,
        rating:4.2,
        discount:18,
        category:"Mobiles",
        link:"/products/33",
        tags:"Best-Seller"
    },
    {
        id:34,
        title:"APPLE iPhone 14",
        desc:"APPLE iPhone 14 (Blue, 128 GB)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/3/5/l/-original-imaghx9qmgqsk9s4.jpeg?q=70",
        price:79900.00,
        rating:4.6,
        discount:14,
        category:"Mobiles",
        link:"/products/34",
        tags:"Top"
    },
    {
        id:35,
        title:"APPLE iPhone 13",
        desc:"APPLE iPhone 13 (Starlight, 128 GB)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/6/n/d/iphone-13-mlpg3hn-a-apple-original-imag6vpyghayhhrh.jpeg?q=70",
        price:69900.00,
        rating:4.7,
        discount:14,
        category:"Mobiles",
        link:"/products/35",
        tags:"Best-Seller"
    },
    {
        id:36,
        title:"Mi 10i",
        desc:"Mi 10i (Midnight Black, 128 GB)  (6 GB RAM)",
        thumbnail:"https://rukminim2.flixcart.com/image/416/416/kjlrb0w0/mobile/6/a/e/mi-10i-m10ix06-original-imafz53gjzqae2kr.jpeg?q=70",
        price:24999.00,
        rating:4.3,
        discount:24,
        category:"Electronics",
        link:"/products/36",
        tags:"Top"
    },
];

export default products;